# Generated by Django 4.1.4 on 2022-12-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'tag', 'verbose_name_plural': 'tags'},
        ),
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(max_length=16, verbose_name='color'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=40, verbose_name='name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='slug'),
            preserve_default=False,
        ),
    ]
